language: rust

matrix:
  include:
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: 1.30.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: 1.30.0
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

    - env: TARGET=thumbv7m-none-eabi
      rust: nightly
      if: (branch = staging OR branch = trying) OR (type = pull_request AND branch = master)

before_install: set -e

script:
  - bash ci/script.sh

after_script: set +e

cache: cargo

before_cache:
  - chmod -R a+r $HOME/.cargo;

branches:
  only:
    - master
    - staging
    - trying

notifications:
  email:
    on_success: never
